export enum Category {
    BRICOLAGE = "BRICOLAGE",
	JARDINAGE = "JARDINAGE",
	DEMENAGEMENT = "DEMENAGEMENT",
	MENAGE = "MENAGE" ,
	AIDE_A_DOMICILE = "AIDE_A_DOMICILE",
	SERVICES_GENERAUX ="SERVICES_GENERAUX"
}
